### PR TITLE
files as emailed from Steve 3/21/22

### PR DESCRIPTION
**Pull request by caver456**
From Steve:

 - [x] 1) Using team assignment get Uncaught exception:  (this was OKay on another try??)

    
11:33:43 [plans_console:1068:INFO] iN LATLOG
11:33:43 [plans_console:1090:INFO] Loc-lat:39.31982226681963 loc-long:-121.06753349304199
11:33:43 [sartopo_python:1351:INFO] getFeatures: No features match the specified criteria.
11:33:43 [sartopo_python:1352:INFO]   (was looking for featureClass=Folder  title=None  id=None)
11:33:43 [plans_console:582:INFO] addMarker folders:[False]
11:33:43 [plans_console:280:CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "C:\Users\steve\Documents\github\plans_Console2\plans_console.py", line 1057, in assignTab_OK_clicked
    self.addMarker()          # uses self.ui.Team, medval
  File "C:\Users\steve\Documents\github\plans_Console2\plans_console.py", line 585, in addMarker
    if folder["properties"]["title"]=="aTEAMS":
TypeError: 'bool' object is not subscriptable

 - [x] 2) Can get several shapes with the same name AA -> AA:1; then recut AA -> AA:1.  Also cut AA:1 -> AA:1:1 versus AA:2 or such Have added code to sequentially add numbers to created features

 - [x] 3) crop leaves the 'cropping' shape  Changed locally

 - [ ] 4) If more than 1 team in an assignment the last team# is kept, not all. Two markers on top of each other. .Shows all team; can remove any one.

 - [x] 5) If more than 1 assignment with the same name AA:1, AA:1, the team marker is placed in one assignment, but the number is not added to either assignment  This should not occur anymore due to check for used numbers

 - [ ] 6) using prior session does not restore the state completely.  Like, the team assignment table.  Also, that table does not populate from the map content when started or if there are items added directly to the map, later.  Seems that items that were in the table get retained.  Could have it update from stuff on the map, too...

 - [x] 7) Beeps are  slow - worked this a bit (online there is issue with delay btwn calls)  Only two beeps now, a bit faster (internet says it will be slow)

 - [x] 8)  feature for cut, etc should only use assignment name, not number 
Made change to getFeatures to only use Letter portion of title

### CODE REVIEW

**Comment by caver456** [comment]
1) looks like no folders existed at the time.  One fix would be to change addMarker to deal with a return value of [False]; another option would be to change getFeatures to return False rather than [False].  That's kind of a dilemma since getFeatures(plural) could be grammatically expected to always return a list as it is currently doing.  Maybe the best, clearest, and most commonly expected option is for getFeatures to return an empty list [] rather than [False].  Will investigate.  Changing getFeatures in either of those manners would allow that part of addMarker to work as currently written.

2) looks like this is related to the blocks at 604-612 and 631-640 and 642 of plans_console.py?  Will investigate.

3) [plans_console.py line 793] - the proposed edit looks fine - might as well go with this level of hardcode for now.  During debrief map generation we don't want to delete the boundary, but maybe when doing a Crop from the plans console GUI you do always want to delete the boundary.  If we determine later that there's a need to make it an option in the GUI, we can do so, though the GUI is pretty compact in that corner so we'd want to think about that.

4) not sure I follow - how about a zoom call and screen share

5) same as 4

6) will investigate here first, but then a zoom call would help to make sure we're talking about the same stuff

7) are you comfortable going to the built-in windows warning chime sounds, instead of the beeps?  Those are much easier to control and eliminate the need for the winsound module and the apparent issues that come with it.  I know it's a change from what you are used to but it's probably for the better.  That's definitely my recommendation.  We could also have it show a modal warning message box.

8) looks like this is the editFlag change in several places in sartopo_python.py?  Will investigate.  Not sure yet what the right place is to add this flexibility.

**Comment by stevelevy** [comment]
For #7, chimes are fine.
    On Tuesday, March 22, 2022, 08:42:46 PM PDT, Tom Grundy ***@***.***> wrote:  
 
 

   
   -    
looks like no folders existed at the time. One fix would be to change addMarker to deal with a return value of [False]; another option would be to change getFeatures to return False rather than [False]. That's kind of a dilemma since getFeatures(plural) could be grammatically expected to always return a list as it is currently doing. Maybe the best, clearest, and most commonly expected option is for getFeatures to return an empty list [] rather than [False]. Will investigate. Changing getFeatures in either of those manners would allow that part of addMarker to work as currently written.

   -    
looks like this is related to the blocks at 604-612 and 631-640 and 642 of plans_console.py? Will investigate.

   -    
[plans_console.py line 793] - the proposed edit looks fine - might as well go with this level of hardcode for now. During debrief map generation we don't want to delete the boundary, but maybe when doing a Crop from the plans console GUI you do always want to delete the boundary. If we determine later that there's a need to make it an option in the GUI, we can do so, though the GUI is pretty compact in that corner so we'd want to think about that.

   -    
not sure I follow - how about a zoom call and screen share

   -    
same as 4

   -    
will investigate here first, but then a zoom call would help to make sure we're talking about the same stuff

   -    
are you comfortable going to the built-in windows warning chime sounds, instead of the beeps? Those are much easier to control and eliminate the need for the winsound module and the apparent issues that come with it. I know it's a change from what you are used to but it's probably for the better. That's definitely my recommendation. We could also have it show a modal warning message box.

   -    
looks like this is the editFlag change in several places in sartopo_python.py? Will investigate. Not sure yet what the right place is to add this flexibility.

**Comment by caver456** [comment]
2) (suffixes for geom op results) is actually in sartopo_python.py, inside the geom ops, and in __init__ (220-233).  Scanning all features for titles is fast enough that we can do it at runtime, inside the geom ops functions, and not bother with doing an initial scan for suffixes during __init__.  Also in the current method, it's just one suffix counter applied globally regardless of unsuffixed title.  So cutting abc by x will make abc:1, then cutting a completely different shape def by z will make def:2.  Change it to find the next available suffix for the base title.  Can reduce the looping a bit by scanning the cache at the beginning of the geom op for all titles that have the same base name, then the new feature(s) can just choose available suffixes based on that list.

**Comment by stevelevy** [comment]
Not sure if this is your notes or a message to me.If you believe you have a better way of doing stuff, go for it.  I thought these items needed to be addressed.  As for numbering new features I think one number pool is sufficient,  but if you want one per item type, Okay.Sent from my Galaxy
-------- Original message --------From: Tom Grundy ***@***.***> Date: 3/24/22  3:00 PM  (GMT-08:00) To: ncssar/plans_console ***@***.***> Cc: Steve Levy ***@***.***>, Review requested ***@***.***> Subject: Re: [ncssar/plans_console] files as emailed from Steve 3/21/22 (PR #11) 

(suffixes for geom op results) is actually in sartopo_python.py, inside the geom ops, and in init (220-233).  Scanning all features for titles is fast enough that we can do it at runtime, inside the geom ops functions, and not bother with doing an initial scan for suffixes during init.  Also in the current method, it's just one suffix counter applied globally regardless of unsuffixed title.  So cutting abc by x will make abc:1, then cutting a completely different shape def by z will make def:2.  Change it to find the next available suffix for the base title.  Can reduce the looping a bit by scanning the cache at the beginning of the geom op for all titles that have the same base name, then the new feature(s) can just choose available suffixes based on that list.

**Comment by caver456** [comment]
Comments on the pull request on the web page automatically get emailed to watchers, so, I'm trying to use that to keep track of the discussion.  Anyway, yeah you always find more gremlins when you peel back the layers, but, 2 is now resolved, as far as I can tell, with the commit a few minutes ago, as well as a few more items on the sartopo_bg big checklist.

**Comment by caver456** [comment]
Got clarification on 4/5/6 on the zoom call.

 4) If more than 1 team in an assignment the last team# is kept, not all. Two markers on top of each other. .Shows all team; can remove any one.

This is really two sub-items that show up when you use the plans console table to indicate that two (or more) teams are working the same assignment, e.g. by filling out the fields '101' 'AA' 'K9' 'Ok'  followed by '102' AA' 'Ground' 'Ok', which makes two rows in the table:

4a) after the first pairing, the sartopo assignment feature 'number' field is set to 101, as expected.  But, after the second pairing, the 101 is clobbered and replaced with 102, when the desired result is that the 'number' field should be set to '101 102', i.e preserving the previous value.  (This does open up the separate question of multiple simultaneous outings in the same assignment, and how to deal with that in dmg.  That's largely a separate question, probably big enough for its own github issue, but will probably have to be addressed at the same time.)

4b) the second pairing makes a second team marker, at the identical location as the first - so only one of them is visible.  While you can still see that there are multiple teams there by hovering (this sometimes shows 'N/A' on CTD 4223) or by left-clicking, so that all features at that location show in the popup, the whole point of the team markers is to have a quick visual indication, with no clicks needed, of what team(s) are in that assignment.  Also, if there is a medical marker, it is not offset - it shows up as the team marker, so, it can be hidden in the same manner.  Some possible solutions - there might be others - just need to try out some ideas:
- offset the markers - probably not a good idea because the markers will be far apart at close zoom but will still mostly overlap at far zoom
- just use one marker total to indicate that an assigment is occupied, and change its label to indicate the name(s) of all occupying team(s); the marker could be medical if any occupying team has medical, or, it could be a separate offset marker
- continue with one marker per team, but pad the labels appropriately so that all team numbers show up visually, i.e. the first label is '101' and the second label is '    102' or such; or change all team markers to have the same label '101 102' - either of these options is confusing in the left bar

 5) If more than 1 assignment with the same name AA:1, AA:1, the team marker is placed in one assignment, but the number is not added to either assignment This should not occur anymore due to check for used numbers

This scenario shouldn't occur any more due to geom ops, but, it could still occur due to the user accidentally drawing multiple assignments with the same letter / title.  So: check for assignment name uniqueness when 'Ok' is clicked, and just pop up an error message with chime if not unique.  To get updated map data, we either need to a) do a fresh since request on 'Ok', and live with the momentary delay before the table is populated etc, or b) sync even without dmg - which would be useful for other reasons too.  a) is easier for now.

 6) using prior session does not restore the state completely. Like, the team assignment table. Also, that table does not populate from the map content when started or if there are items added directly to the map, later. Seems that items that were in the table get retained. Could have it update from stuff on the map, too...

It seems to be restoring everything now so maybe that was just a fluke, we will keep an eye out for it going forward.  But the separate suggestion stands, to have the table automatically populate based on assignment features on the map.  This would also require sync without dmg, and would somewhat expand the idea of what should be in the table: right now it's one row per pairing, but, would this suggestion mean that it should be one row per assignment, both assigned and unassigned - in which case the 'new pairing entry method' would be somewhat different?  Before pursuing this, maybe review the Assignment Tracker repo to see if that UI technique is useful.

**Comment by caver456** [comment]
Game plan for right now:
4a) fix now, and assess the multiple-simultaneous-outings issue
4b) brainstorm / postpone
5) fix now, using option a) (do a since request when Go is clicked, then check for uniqueness)
6) brainstorm / postpone

**Comment by caver456** [comment]
The last commit was intended to fix item 5, and it does; apparently it also fixed item 4a - not exactly sure why but we can call the first part of 4a done: adding a second team to e.g. assignment AA results in number value = '101 102' and full title in left bar = 'AA 101 102'.  Markers are also added as expected though this doesn't address the desired improvements from 4b.

Like it says in 4a, there's probably still some work to do on this branch to get multiple-simultaneous-outings-in-same-assignment working.

**Comment by caver456** [comment]
decisions for the final commit in this branch a few minutes ago:
- plans console table actions are not generating dmg outings.  This is in the gray area between bug and feature request, but, in order to merge and move on quickly, this is not being addressed in this branch.
- plans console table 'RM' does not seem to remove the team number from assignments that contain it.  It's not completely clear that this ever worked, so, also not being addressed in this branch.

**Review by caver456 — COMMENTED** [review]
all looks good

**Pull request merged**
